### ISSUE TITLE
Peer dependency missing for Antwar

### ISSUE THREAD

**Issue by PEM--** [antwarjs/antwar#102]
As recommended, I've installed `antwar-cli` globally and when I try to initialize a site, I got:
```sh
antwar --init antwar-test
module.js:340
    throw err;
    ^

Error: Cannot find module 'antwar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/antwar-cli/index.js:9:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by bebraw** [comment]
I think you may need to install `antwar` globally as well.

I have a big rewrite going on that will simplify the process greatly and improve the tool somewhat. It might  not be the best time to begin to use it yet.

I'll leave this issue open for now and let you know when the new version is out. Thanks for your patience. :+1:

**Comment by PEM--** [comment]
No pb. Great idea, love the concept and thanks for making it public.

**Comment by knpwrs** [comment]
Can confirm that I had to install `antwar` globally in order for `antwar-cli` to work.

**Comment by bebraw** [comment]
Local install should work again so I'm closing this. Let me know if you encounter any issues.

A part of the tooling (boilerplate etc.) might be broken but the core and the cli should be solid now that there's active development.
