### ISSUE TITLE
ERROR in Cannot find module './_baseClone'

### ISSUE THREAD

**Issue by coopnickol** [antwarjs/antwar#105]
Getting this as a result from `antwar -d`

```bash
> developer@0.0.0-alpha start C:\Users\ncoop\_io\docs\antwar
> antwar -d

2016.08.12.10.01.44 Start developing

2016.08.12.10.01.44
Developing failed
ERROR in Cannot find module './_baseClone'

ERROR in Cannot find module './_baseClone'
2016.08.12.10.01.44
Time elapsed: 812 ms
```

I have not been able to find where that module even lives....I'm modeling after webpack 2's new documentation site.

**Comment by bebraw** [comment]
Hi,

That's a new one. Could you push your project to GitHub so I can have a closer look?

**Comment by coopnickol** [comment]
My [developer branch](/CIMRO/developer/tree/develop) is most up to date. I let this issue sit over the weekend and came back to a whole bunch of `Module parse failed` errors.
```javascript
ERROR in ./layouts/Body.jsx
Module parse failed: C:\Users\ncoop\_io\docs\antwar\layouts\Body.jsx Unexpected token (17:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (17:6)
    at Parser.pp$4.raise (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (C:\Users\ncoop\_io\docs\antwar\node_modules\acorn\dist\acorn.js:1796:19)
 @ ./antwar.config.js 23:16-41
```

After fiddling with a few things, got it all cleaned up and functioning......unfortunately none of that is helpful to this issue........After googling it I still have no idea where the _baseClone module even lives.  I'll reopen if it shows up again........................

Just for information's sake I'm using nvm:
```bash
  6.2.2
  * 5.11.0 (Currently using 64-bit executable)
    4.4.7
    4.4.3
    4.2.1
```
And I didn't play with anything when I came back to it this morning.......

**Comment by bebraw** [comment]
Cool to hear you got it working. Maybe I can simplify Antwar further. Less can go wrong that way. 👍
