### ISSUE TITLE
console.info undefined

### ISSUE THREAD

**Issue by winkler1** [antwarjs/antwar#36]
Did the following

```
npm install -g antwar-cli
antwar --init rrocks_blog
```
Errors out--
```
/usr/local/lib/node_modules/antwar-cli/lib/init.js:13
    console.info('Fetching boilerplate metadata');
            ^
TypeError: Cannot call method 'info' of undefined
  at Object.module.exports [as init] (/usr/local/lib/node_modules/antwar-cli/lib/init.js:13:13)
  at main (/usr/local/lib/node_modules/antwar-cli/index.js:49:13)
  at Object.<anonymous> (/usr/local/lib/node_modules/antwar-cli/index.js:13:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:11
```

**Comment by eldh** [comment]
@bebraw related to the thing you did with console? We need to publish new versions of everything btw.

**Comment by bebraw** [comment]
@eldh Yeah, let me release new versions so everything is up to date. Lots of changes.

**Comment by bebraw** [comment]
@winkler1 Just published new versions. There are likely problems still. At least hot loading should be broken at the moment (to be debugged). Let me know if/when you find glitches.
