### ISSUE TITLE
antwar --develop fails, missing lodash

### ISSUE THREAD

**Issue by dermike** [antwarjs/antwar#64]
After following the instructions at http://antwarjs.github.io/get-started/
I get this error when trying to run antwar --develop:

/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:24025
"Cannot find module \"lodash\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                     ^
Error: Cannot find module "lodash"
  at webpackMissingModule (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:24025:70)
  at Object.<anonymous> (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:24025:153)
  at __webpack_require__ (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:21:30)
  at Object.<anonymous> (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:38108:23)
  at __webpack_require__ (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:21:30)
  at Object.<anonymous> (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:49481:20)
  at __webpack_require__ (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:21:30)
  at Object.module.exports._prototypeProperties (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:49542:15)
  at __webpack_require__ (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:21:30)
  at Object.<anonymous> (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:72:15)
  at __webpack_require__ (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:21:30)
  at module.exports.modules.(anonymous function) (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:41:18)
  at Object.<anonymous> (/Users/mike/Documents/old-blog/.antwar/build/bundleStaticPage.js:44:10)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/build/dev_index.js:22:26
  at Tapable.<anonymous> (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:192:14)
  at Tapable.emitRecords (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:279:37)
  at Tapable.<anonymous> (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:185:11)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:272:11
  at Tapable.applyPluginsAsync (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Tapable.afterEmit (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:269:8)
  at Tapable.<anonymous> (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:264:14)
  at done (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/async/lib/async.js:135:19)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/async/lib/async.js:32:16
  at /usr/local/lib/node_modules/antwar-cli/node_modules/gh-pages/node_modules/graceful-fs/graceful-fs.js:103:5
  at Object.oncomplete (fs.js:107:15)

**Comment by eldh** [comment]
Lodash was missing as a dependency in default-theme. Haven't been able to reproduce but the dependency is added in v0.2.3 of default-theme.

**Comment by dermike** [comment]
That solved it!
