### ISSUE TITLE
Error: Cannot find module "./scss/main.scss" after --init new project

### ISSUE THREAD

**Issue by doobleweb** [antwarjs/antwar#94]
steps:
```
npm i antwar-cli -g
antwar --init koko

➜  koko  antwar -d
Start developing

/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:37691
	__webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"./scss/main.scss\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
	                                                                                                                                                   ^

Error: Cannot find module "./scss/main.scss"
  at webpackMissingModule (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:37691:66)
  at Object.<anonymous> (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:37691:159)
  at __webpack_require__ (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:21:30)
  at Object.module.exports.handlers.body (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:21863:15)
  at Object.<anonymous> (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:49961:75)
  at __webpack_require__ (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:21:30)
  at Object.<anonymous> (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:50140:19)
  at __webpack_require__ (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:21:30)
  at Object.<anonymous> (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:74:15)
  at __webpack_require__ (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:21:30)
  at /Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:41:18
  at Object.<anonymous> (/Users/asafkatz/Development/koko/.antwar/build/bundleStaticPage.js:44:10)
  at Module._compile (module.js:434:26)
  at Object.Module._extensions..js (module.js:452:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/build/dev_index.js:22:26
  at Compiler.<anonymous> (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:194:14)
  at Compiler.emitRecords (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:282:37)
  at Compiler.<anonymous> (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:187:11)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:275:11
  at Compiler.applyPluginsAsync (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
  at Compiler.afterEmit (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:272:8)
  at Compiler.<anonymous> (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/lib/Compiler.js:267:14)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/node_modules/async/lib/async.js:52:16
  at done (/usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/node_modules/async/lib/async.js:248:21)
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/webpack/node_modules/async/lib/async.js:44:16
  at /usr/local/lib/node_modules/antwar-cli/node_modules/gh-pages/node_modules/graceful-fs/graceful-fs.js:103:5
  at /usr/local/lib/node_modules/antwar-cli/node_modules/antwar/node_modules/cpr/node_modules/graceful-fs/graceful-fs.js:42:10
  at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by bebraw** [comment]
Thanks for the report.

I noticed the default theme had some unpublished changes. I bumped the version and published those.

Can you try reinstalling the theme to your project and see if that helps?

Alternatively you could try to hook up the [clean theme](https://github.com/antwarjs/clean-theme).

**Comment by doobleweb** [comment]
Works now. thanks (:
